### ISSUE TITLE
Getting UnicodeDecodeError

### ISSUE THREAD

**Issue by kivysyar** [MihanEntalpo/allure-single-html-file#17]
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf1 in position 14759: invalid continuation byte
![image](https://user-images.githubusercontent.com/93857414/181490196-addddb16-44fc-4654-a3ce-fce124fdbef0.png)

**Comment by kivysyar** [comment]
[allure-report.zip](https://github.com/MihanEntalpo/allure-single-html-file/files/9208588/allure-report.zip)

**Comment by MihanEntalpo** [comment]
Hello. It seems that some file is not in utf-8 encoding, and my tool cannot handle it (As I haven't such files). Will try your archive, and see what can be done

**Comment by kivysyar** [comment]
@MihanEntalpo , Yeah I wonder why the file is getting generated without utf-8 encoding. Have you got some time to look into the issue?

**Comment by MihanEntalpo** [comment]
Hi! I've discovered, that the problem appears when some file have non-utf8 encoding. There are three methods of bypass this:

1. Force utf-8 encoding while reading file contents, so non-utf8 characters would be replaced by "?" or spaces.
2. Work with files as binary (bytearray, not str), and so skip any encoding failure, because no file decoding means no problems. It could make some problems with beautifulsoup, as I'm not sure, it can work without encoding with raw bytes.
3. Detect encoding with some of the great python libraries, and use it for each file.

I'll make some experiments to know what solution would be the best

**Comment by MihanEntalpo** [comment]
@kivysyar sorry for long time passed till the solution, but I've made it.
Now, if your files has wrong encoding, you'll get messages like:
```
Error on reading file data/attachments/ea3461185f8d737f.json: 'utf-8' codec can't decode byte 0xea in position 7071: invalid continuation byte. Use --ignore-utf8-errors argument to skip this type of errors
```
and files just wont be added to combined file.

You must specify argument `--ignore-utf8-errors` so, all utf-8 errors would be ignored and files would be imported into a single combined file. There are new 1.0.7 version on pip.

**Comment by kivysyar** [comment]
Appreciate your support in this regard, works like charm!
