### ISSUE TITLE
Not an issue, just feature request  

### ISSUE THREAD

**Issue by yaront1111** [MihanEntalpo/allure-single-html-file#22]
i arrived here because im trying to send an html email with allure summery .. 

im using Jenkins and it will be amazing if there was a way to send Email summary notification..

**Comment by MihanEntalpo** [comment]
Hello. 
This script is intended to follow KISS principle ("keep it simple, stupid!"), so it's a single tool made for single task.
Sending email would be completly out of its scope, and in *nix system could be easily achieved via other tools. 

I'm not an experienced user of Jenkins, but I think that in its pipeline instead of running allure-combine, you can run some bash-script, that in it's turn should run allure-combine, and after that send generated report via some console email client (https://www.digitalocean.com/community/tutorials/send-email-linux-command-line)

**Comment by yaront1111** [comment]
Hi i didnt mean the script send the email.. just to make the html file ..
with summry that suitable to support html email..

**Comment by MihanEntalpo** [comment]
Ok, I understood now.
I think that viewing allure report in a email is not possible, because subset of html, JS and css usable in emails is quite limited, and so, complex single-page applications such as allure report, could  ot be viewed in email.
Of course, it is possible to make some kind of "multi-page layout" to see all the data in allure report page without need of opening links, tabs on it, but this re-layouting is out of scope of my humble script, which is just takes existing html file, it's requirements (JS, css, csv, jpeg, gif, etc.) and combines it into one file.

If you have any thoughts on hot to achieve your goal another way, Id be glad to know

**Comment by MihanEntalpo** [comment]
According to this merged pull request https://github.com/allure-framework/allure2/pull/2072 Allure itself now has command line argument --single-file that make it produce report as a single html file. As for now it's not described in official allure docs, but anyway it should make this package (allure-combine) useless. I'm encorage you to use Allure --single-file functionality, as it should work much better that my combiner!
