### ISSUE TITLE
file 'complete.html' without any data

### ISSUE THREAD

**Issue by ZYist** [MihanEntalpo/allure-single-html-file#27]
Hey guys,

I just followed all the steps to export a single html file,
but the file is empty, all tabs are "loading" without any data.

If I use command $ allure serve allure-report/,
it worked well and I could check every test.

Does anyone meet this like me ?

pyton 3.6, pytest 7.0.1, allure-pytest 2.13.2

**Comment by MihanEntalpo** [comment]
Hello. It's not "empty", it's just got some JavaScript error caused by some kind of problem in file generation. In your browser devtools console you should see some error messages when opening the file.
To check your case I need your allure generated folder to check it myself (just after it was generated, not after combine script was run).
Could you attach it as an archive?

**Comment by ZYist** [comment]
Thanks for you rapid reply my friend !!!

All you want is in the attachment.

Btw thank you again !!!

[allure-report.zip](https://github.com/MihanEntalpo/allure-single-html-file/files/11876791/allure-report.zip)

**Comment by ZYist** [comment]
Sorry dude its forbidden to share the test report out of company.

My idea is to build an environment just as yours.

Could you leave a list that contains all the versions of shit like ide, Python, pytest, plugins, etc.

Anyway thanks a bunch !

**Comment by MihanEntalpo** [comment]
My envoronment wont give you any help, because I'm not running tests, not using allure, and this tool is written for other people who are running tests. 
So, you could create minimal reproducible example, for example, create single test case, which doint `assert True`, run it, create allure report, try to make allure-combine, and if it's also generating wrong data, you can share it, because, usually problems cause by some new features of allure, for example, in other issue (#26) where were problem with allure adding google tag manager script into allure html file.

**Comment by ZYist** [comment]
many thanks my friend.

it could export single html with simple test case.

but fail when too many test cases were runing up.

**Comment by MihanEntalpo** [comment]
Try to open browser DevTools console, and look, are there any errors in Console tab, or Network tab. Is there are any - make screenshot and post it here, if needed, wipe out any sensitive information from it

**Comment by MihanEntalpo** [comment]
Thanks for the example, it seems, that some of the files not being embedded into resulting complete.html, I'll check it.

**Comment by shwetankverma** [comment]
for me also the same issue. complete.html without any data, total blank

**Comment by MihanEntalpo** [comment]
@shwetankverma please, attach your allure report folder, before allure-combine was executed (e.g. unchanged report folder)

**Comment by shwetankverma** [comment]
Sorry I cant , its forbidden to share the test report out of company.
However, in the Devtools console I am getting this(attached).

But this was working till 2 days back and suddenly stopped without any changes.
I am using allure 2.14.0

Please help

**Comment by MihanEntalpo** [comment]
Thanks for your information, I'll try to look into this, and maybe ask you for the additional info

**Comment by shwetankverma** [comment]
Hi @MihanEntalpo Any update on this issue?

**Comment by MihanEntalpo** [comment]
I'll try to solve this in a three days

**Comment by MihanEntalpo** [comment]
Hello, everyone. I've found stupid bug, that I've made in previous version.
New version 1.0.11 without this bug is already in pypi repo, so you can update it and try out.
All the examples in this thread now working fine.

If your report doesn't work, feel free to reopen this issue
